local_app_path: &local_app_path /usr/app
local_artifacts_path: &local_artifacts_path !join [*local_app_path, /artifacts]
local_data_path: !join [*local_artifacts_path, /breast-cancer-wisconsin-data.zip]
conda_environment_path: !join [*local_app_path, /environment.yaml]
mlflow_experiment_name: lr.1.0
target_column: diagnosis
drop_columns: id
train_size: 0.9
model_type: linear_model.LogisticRegression
n_iterations: 5
model_parameters:
  C:
    uniform: [0.2, 1]
  penalty:
    choice: [l1, l2, elasticnet]